- hosts: "{{ n }}"
  tasks:

    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.nodes }}"

    - name: Changing Hostname to "{{ n }}"
      replace:
        path: /etc/hostname
        regexp: '.*$'
        replace: "{{ n }}"
      register: reboot_req

    - name: Reboot immediately if there was a change in reboot_req.
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: reboot_req is changed

    - name: Wait for the reboot to complete if there was a change in reboot_req.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: reboot_req is changed

    - name: Ping "{{ n }}" to check if it's online
      ping: "{{ n }}"

