- hosts: localhost
  vars:
    count: 1
    name: "prod_tv_{{tag}}"
    type: t2.medium
    tag: master
  roles:
     - { role: launch-instances }
- hosts: localhost
  vars:
    count: 2
    name: "prod_tv_{{tag}}"
    type: t2.micro
    tag: worker
  roles:
     - { role: launch-instances }
