- hosts: masters
  become_user: kube
  tasks:

    - name: Deleting Deployment, Service, HPA of my_app
      shell: kubectl delete deploy,svc,hpa "{{ item }}"
      with_items:
        - blue
        - green
      ignore_errors: yes

    - name: deploying HPA my_app
      shell: kubectl create -f "{{ item }}"
      with_items:
        - /home/kube/kubernetes/blue/
        - /home/kube/kubernetes/green/
      ignore_errors: yes

