- hosts: ec2
  become: yes
  tasks:

  - name: Removing repo file for kubernetes
    file:
      path: /etc/yum.repos.d/kubernetes.repo
      state: absent

  - name: Create repo file for kubernetes
    file:
      path: /etc/yum.repos.d/kubernetes.repo
      state: touch

  - name: Editing repo file for kubernetes
    blockinfile:
      path: /etc/yum.repos.d/kubernetes.repo
      block: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=0
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg  

  - name: install Docker
    shell: amazon-linux-extras install -y docker

  - name: Restart Docker
    service: 
      name: docker
      state: restarted

  - name: install kubelet, kubeadm
    yum:
      name: kubelet, kubeadm
      state: latest
      disable_excludes: kubernetes
      update_cache: yes

  - name: Enabling kubelet
    shell: systemctl enable --now kubelet && systemctl enable docker.service
