- hosts: ec2
  become: yes
  tasks:

   - name: install Docker
     shell: amazon-linux-extras install -y docker

   - name: Restart Docker
     service: 
       name: docker
       state: restarted

   - name: install kubelet
     yum:
       name: kubelet, kubeadm, kubectl
       state: present
       disableexcludes: kubernetes
