- hosts: ec2
  become: yes
  tasks:

  - name: install Docker
    shell: amazon-linux-extras install -y docker

  - name: Restart Docker
    service: 
      name: docker
      state: restarted

  - name: Create repo file for kubernetes
    file:
      path: /etc/yum.repos.d/kubernetes.repo
      state: touch

  - name: Editing repo file for kubernetes
    blockinfile:
      path: /etc/ssh/sshd_config
      block: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg  

  - name: Set SELinux in permissive mode (effectively disabling it)
    shell: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

  - name: install kubelet
    yum:
      name: kubelet, kubeadm, kubectl
      state: present
      disable_excludes: kubernetes
      update_cache: true

  - name: Enabling kubelet
    shell: systemctl enable --now kubelet
