- hosts: ec2
  become: yes
  tasks:

   - name: install Docker
     shell: amazon-linux-extras install -y docker

   - name: Restart Docker
     service: 
       name: docker
       state: restarted

   - name: Adding repo for kubernetes
     copy:
       src: /home/ec2-user/kubeadm/files/kubernetes.repo
       dest: /etc/yum.repos.d/kubernetes.repo
       remote_src: yes

   - name: install kubelet
     yum:
       name: kubelet, kubeadm, kubectl
       state: present
       disable_excludes: kubernetes
