- hosts: ec2
  become: yes
  tasks:
  gather_facts: no
  
    - name: Installing pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Installing Openshift for k8s modules
      pip:
        name: openshift

    - name: Removing previous nginx depolyment, HPA, Service and configmap
      become_user: kube
      k8s:
        state: absent
        src: /home/kube/kubernetes/php-app/{{w}}/{{w}}-nginx/

    - name: Removing previous php depolyment, HPA, Service and configmap
      become_user: kube
      k8s:
        state: absent
        src: /home/kube/kubernetes/php-app/{{w}}/{{w}}-php/

    - name: removing previous kubernetes folder
      file:
        path: /home/kube/kubernetes
        state: absent

    - name: download my repo kubernetes
      become_user: kube
      git:
        repo: https://github.com/hiakki/kubernetes.git
        dest: /home/kube/kubernetes
      ignore_errors: yes

    - name: Changing External IP
      replace:
        path: /home/kube/kubernetes/php-app/launch.sh
        regexp: 'masterIP'
        replace: "{{ansible_host}}"

    - name: deploying app
      become_user: kube
      shell: "cd /home/kube/kubernetes/php-app/ && sh launch.sh {{w}}"
