- hosts: ec2
  tasks:

    - name: create the 'kube' user
      user: 
        name: kube 
        append: yes 
        state: present 
        createhome: yes 
        shell: /bin/bash

    - name: allow 'kube' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the kube user
      authorized_key: user=kube key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub

    - name: Create a Directory /home/kube/logs
      file:
        path: /home/kube/logs
        state: directory
        mode: 0777
