---

    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

    - name: Saving token in a file
      debug:
        msg: "{{ join_command }}"


#- hosts: "tag_node_worker"
#  become: yes
#  tasks:

#    - name: join cluster
#      shell: "{{ hostvars['master'].join_command }}"
#      ignore_errors: yes
