- hosts: ec2
  become: yes
  tasks:

    - name: initialize the cluster
      shell: kubeadm init >> configure-master-node1.txt
      args:
        chdir: /home/kube/logs
        creates: cluster_initialized1.txt
      ignore_errors: yes

    - name: create .kube directory
      file:
        path: /home/kube/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube

    - name: install Pod network
      become_user: kube
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')" >> configure-master-node2.txt
      args:
        chdir: /home/kube/logs
        creates: configure-master-node2.txt

    - name: download metrics-server from kubernetes-incubator
      become_user: kube
      git:
        repo: https://github.com/kubernetes-incubator/metrics-server.git
        dest: /home/kube/metrics-server
      ignore_errors: yes

    - name: download metrics-server-deployment.yaml from my repo
      become_user: kube
      get_url:
        url: https://raw.githubusercontent.com/hiakki/kubernetes/master/metrics-server/metrics-server-deployment.yaml
        dest: /home/kube/metrics-server/deploy/1.8+/

    - name: Deploying Metrics-Server for HPA
      become_user: kube
      shell: kubectl apply -f /home/kube/metrics-server/deploy/1.8+/ >> deploy-metrics-server-for-HPA1.txt
      args:
        chdir: $HOME/logs
        creates: deploy-metrics-server-for-HPA1.txt
