- hosts: ec2
  become: yes
  tasks:

    - name: download my repo kubernetes
      become_user: kube
      git:
        repo: https://github.com/hiakki/kubernetes.git
        dest: /home/kube/kubernetes
      ignore_errors: yes

    - name: Changing External IP
      replace:
        path: /home/kube/kubernetes/php-app/launch.sh
        regexp: 'masterIP'
        replace: " {{ ansible_host }}"
        backup: yes

    - name: deploying app
      shell: sh /home/kube/kubernetes/php-app/launch.sh
      ignore_errors: yes
