- hosts: ec2
  become: yes
  tasks:

    - name: download my repo kubernetes
      become_user: kube
      git:
        repo: https://github.com/hiakki/kubernetes.git
        dest: /home/kube/kubernetes
      ignore_errors: yes

    - name: Get Master Node's IP
      shell: ifconfig eth0 | grep 'inet ' | awk {'print $2'}
      register: get_ip

    - name: Set Master Node's IP
      set_fact:
        set_ip: "{{ get_ip.stdout_lines[0] }}"

    - name: Changing External IP
      replace:
        path: /home/kube/kubernetes/php-app/launch.sh
        regexp: 'masterIP'
        replace: " {{ hostvars['master'].set_ip }}"
        backup: yes

    - name: deploying app
      shell: sh /home/kube/kubernetes/php-app/launch.sh
      ignore_errors: yes
