- hosts: master
  become_user: kube
  tasks:

    - name: Get Master Node's IP
      shell: ifconfig eth0 | grep 'inet ' | awk {'print $2'}
      register: get_ip

    - name: Set Master Node's IP
      set_fact:
        set_ip: "{{ get_ip.stdout_lines[0] }}"

    - name: Changing External IP
      replace:
        path: "{{ item }}"
        regexp: 'masterIP'
        replace: " {{ hostvars['master'].set_ip }}"
        backup: yes
      with_items: 
        - /home/kube/kubernetes/blue/nginx_php-fpm_multicontainer_service.yaml
        - /home/kube/kubernetes/green/nginx_php-fpm_multicontainer_service.yaml

    - name: deploying HPA my_app
      shell: kubectl create -f "{{ item }}"
      with_items: 
        - /home/kube/kubernetes/blue/
        - /home/kube/kubernetes/green/
      ignore_errors: yes
